# Generated by Django 5.0.7 on 2024-07-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('company_clients', models.TextField()),
            ],
        ),
    ]
